---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  description: This task will echo the message.
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [/bin/echo]
      args: ["$(params.message)"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all of the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  description: This task will lint the Python code using flake8.
  workspaces:
    - name: source
  params:
    - name: image
      description: The container image to use
      type: string
      default: "python:3.9-slim"
    - name: args
      description: Arguments to pass to flake8
      type: string
      default: "--count --max-complexity=10 --max-line-length=127 --statistics"
  steps:
    - name: lint
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Installing flake8..."
        pip install flake8 -q
        echo "Running flake8 linter..."
        flake8 service tests $(params.args)
        echo "Linting passed!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pytest
spec:
  description: This task will run unit tests using pytest/nose.
  workspaces:
    - name: source
  params:
    - name: image
      description: The container image to use
      type: string
      default: "python:3.9-slim"
    - name: database_uri
      description: The database URI for testing
      type: string
      default: "sqlite:///test.db"
  steps:
    - name: test
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABASE_URI
          value: $(params.database_uri)
      script: |
        #!/bin/bash
        set -e
        echo "Installing dependencies..."
        pip install -r requirements.txt -q
        echo "Running unit tests with nose..."
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=service
        echo "Tests passed!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  description: This task builds and pushes an image using Buildah.
  workspaces:
    - name: source
  params:
    - name: IMAGE
      description: The fully qualified image name
      type: string
    - name: DOCKERFILE
      description: Path to the Dockerfile
      type: string
      default: "./Dockerfile"
    - name: CONTEXT
      description: Path to the build context
      type: string
      default: "."
    - name: TLSVERIFY
      description: Verify TLS on the registry
      type: string
      default: "false"
    - name: FORMAT
      description: The format of the built container
      type: string
      default: "oci"
    - name: BUILD_EXTRA_ARGS
      description: Extra arguments for buildah build
      type: string
      default: ""
    - name: PUSH_EXTRA_ARGS
      description: Extra arguments for buildah push
      type: string
      default: ""
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.28
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      script: |
        #!/bin/bash
        set -e
        echo "Building image $(params.IMAGE)..."
        buildah --storage-driver=vfs bud \
          --format=$(params.FORMAT) \
          --tls-verify=$(params.TLSVERIFY) \
          $(params.BUILD_EXTRA_ARGS) \
          -f $(params.DOCKERFILE) \
          -t $(params.IMAGE) \
          $(params.CONTEXT)
        echo "Build complete!"

    - name: push
      image: quay.io/buildah/stable:v1.28
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      script: |
        #!/bin/bash
        set -e
        echo "Pushing image $(params.IMAGE)..."
        buildah --storage-driver=vfs push \
          --tls-verify=$(params.TLSVERIFY) \
          $(params.PUSH_EXTRA_ARGS) \
          --digestfile /tmp/image-digest \
          $(params.IMAGE) \
          docker://$(params.IMAGE)
        cat /tmp/image-digest | tee $(results.IMAGE_DIGEST.path)
        echo "Push complete!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-image
spec:
  description: This task will deploy the application to OpenShift.
  workspaces:
    - name: source
  params:
    - name: image_name
      description: The fully qualified image name
      type: string
    - name: manifest_dir
      description: The path to the Kubernetes manifests
      type: string
      default: "deploy"
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        echo "Deploying application..."
        
        # Update the deployment with the new image
        if [ -f $(params.manifest_dir)/deployment.yaml ]; then
          echo "Applying deployment manifests from $(params.manifest_dir)..."
          sed -i "s|IMAGE_NAME|$(params.image_name)|g" $(params.manifest_dir)/deployment.yaml
          oc apply -f $(params.manifest_dir)/deployment.yaml
        fi
        
        if [ -f $(params.manifest_dir)/service.yaml ]; then
          echo "Applying service manifest..."
          oc apply -f $(params.manifest_dir)/service.yaml
        fi
        
        if [ -f $(params.manifest_dir)/route.yaml ]; then
          echo "Applying route manifest..."
          oc apply -f $(params.manifest_dir)/route.yaml
        fi
        
        echo "Waiting for deployment to complete..."
        oc rollout status deployment/accounts --timeout=300s
        echo "Deployment complete!"
